# run: conda env create --file environment.yml
name: leveldensities
dependencies:
- python>=3.9
- anaconda
- pip
- numpy
- gunicorn
- pandas
- pip:
  - dash>=1.0.0
  - colorlover>=0.2.1
  - dash-bootstrap-components==1.0.2
